### ISSUE TITLE
Multiple accounts drops doesn't work

### ISSUE THREAD

**Issue by Loran0** [awekrx/AFK-Twitch-drops#2]
Here is an example of my tokens config:

"tokens": ["555555555", "666666666"],

I logged in with 1st account, get auth token, log out, log in with 2nd account, get auth token. Then close chromium.
Unfortunately, after 'node index.js' it starts running, then Finding streamers... and that's it - endless Finding streamers without any further messages.
Any ideas?

**Comment by awekrx** [comment]
Most likely, something has changed on twitch in half a year, so it doesn’t work or you are trying to look in a category where there are no drops.

**Comment by awekrx** [comment]
I checked, everything works. Try not to log out of your account after receiving the cookie. Most likely after the exit they change and you do not have authorization.
![image](https://user-images.githubusercontent.com/56741415/223680005-89444551-3f20-4d54-a618-db1a59aebc52.png)

**Comment by Loran0** [comment]
But how can I login into BOTH accounts in one browser without logging out? Or should I use an incognito tab?

**Comment by awekrx** [comment]
yeah, use the incognito tab

**Comment by Loran0** [comment]
Here we go! Now it works. i believe every account should be opened and logged in using the new incognito tab.
Thank you for your help!

btw... after all night of 'watching' twitch :D i noticed that the last drop wasn't claimed. For example - there are 6 drops and i can get every new drop after 4 hours of watching the stream.  First 5 drops were claimed successfully. Last one - wasn't claimed. I just open the browser and claim it by myself. Dunno is it a bug or it should be like that.
I will check again when the next drops will be available. Thanks again.

**Comment by awekrx** [comment]
Thank you very much for the feedback, I've added a message if authorization via cookies does not work.
