### ISSUE TITLE
Hello, I separated two Twitch accounts with commas, but only the first account will progress with the drop, and the second account has no response.

### ISSUE THREAD

**Issue by 1279494766** [awekrx/AFK-Twitch-drops#4]
And it doesn't seem to automatically claim drops
![1690102400700](https://github.com/awekrx/AFK-Twitch-drops/assets/128236168/12445611-54e8-45b2-a1e8-1472729aec61)

**Comment by awekrx** [comment]
Try changing `browsers` parameter in config to `true,`. And see how the second account works and tell me what troubles with it.

```js
    "browsers": true,
```

**Comment by 1279494766** [comment]
The first image shows my two accounts, while the second image shows that only one account is watching and the second account has no response
![1690103775674](https://github.com/awekrx/AFK-Twitch-drops/assets/128236168/24b5c49c-cf6d-4541-b925-828db1dd014a)
![1690103816548](https://github.com/awekrx/AFK-Twitch-drops/assets/128236168/68bd355e-45cc-4daa-83c2-b21a822f1fc4)

**Comment by awekrx** [comment]
How can see the thread works means the problem is not in this software

**Comment by 1279494766** [comment]
Okay, but I have another question. It seems like it can watch automatically, but it cannot automatically claim drops。May I ask if my settings are not turned on?
![1690125536868](https://github.com/awekrx/AFK-Twitch-drops/assets/128236168/8b7a5fc2-f64b-42ab-80f1-46478f7b9ee8)

**Comment by awekrx** [comment]
I checked reason this problem. Its happen because twitch changed drops-claim method. I haven't time to fix this now. Try use other similar app.
