### ISSUE TITLE
MaxListenersExceededWarning

### ISSUE THREAD

**Issue by ftugit** [awekrx/AFK-Twitch-drops#5]
![2023-09-07_014430](https://github.com/awekrx/AFK-Twitch-drops/assets/17074693/e7c357ec-7ba4-4e56-a1a7-72940cc7cefc)

**Comment by ftugit** [comment]
I have created several instances of the program and everything works. Changing the configuration in each instance takes a long time and therefore I will be glad if there is a fix.

**Comment by ftugit** [comment]
If you run the program with a shortage of RAM, the browser freezes along with AFK-Twitch-drops.

**Comment by ftugit** [comment]
If this is important, then I have 4 instances of the program with 5 authorizations. I have 32 GB of RAM, and about 25 GB of it is free before the program starts.

**Comment by awekrx** [comment]
Fixed
