### ISSUE TITLE
Does not collect drops

### ISSUE THREAD

**Issue by ftugit** [awekrx/AFK-Twitch-drops#6]
firstly, the button does not see, had to be changed to
`const dropsSelector = 'button[class="ScCoreButton-sc-ocjdkq-0 ScCoreButtonPrimary-sc-ocjdkq-1 buUmIQ bxHedf"]';`
secondly, the drop does not collect. if you turn on the browser mode, twitch gives an error when trying to pick up.

**Comment by awekrx** [comment]
I updated selector but drops are still not collected. Twitch most likely added protection.
